apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
    name: my-autoscaler
spec:
    scaleTargetRef:
        apiVersion: apps/v1
        kind: Deployment
        name: demo-ui
    minReplicas: 1
    maxReplicas: 5
    targetCPUUtilizationPercentage: 60
